title: "Chicago Crime Dynamics: Spatio-Temporal Analysis of Trends and Hotspots"
description: "Iker Sanchez & Drew Flinn."
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
